### ISSUE TITLE
Embeddable by python3?

### ISSUE THREAD

**Issue by catroot** [Restream/reindexer#5]
Is there a way to compile a shared library of the reindexer and use with python3?

While trying to build a shared lib i've got this:
```
go build -buildmode=shared
# /tmp/go-build928009316/lib_-sandbox1-Compile-reindexer.so
warning: unable to find runtime.a
warning: unable to find runtime/cgo.a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0x517fa9]

goroutine 1 [running]:
cmd/link/internal/ld.decodetypeSize(0x6f8060, 0x0, 0x609940)
        /usr/local/go/src/cmd/link/internal/ld/decodesym.go:78 +0x29
cmd/link/internal/ld.(*Link).symtab(0xc4204da000)
        /usr/local/go/src/cmd/link/internal/ld/symtab.go:690 +0x28fb
cmd/link/internal/ld.Main()
        /usr/local/go/src/cmd/link/internal/ld/main.go:218 +0x9ec
main.main()
        /usr/local/go/src/cmd/link/main.go:58 +0xac

```
`go version go1.9.4 linux/amd64`

May be there some tricks needed to achieve an elf shared library with headers? 

`go build -o libreindexer.so -buildmode=c-shared` some how produces ar archive instead of elf binary.

**Comment by olegator77** [comment]
Hi, 
The reindexer library is written in pure c++. So, you need cmake and g++ compiler to build it. 

To download and compile library use the following sequence:

````bash
git clone https://github.com/restream/reindexer
cd reindexer/cpp_src
mkdir -p build
cd build
cmake ..
make reindexer -j4
````
After this libreindexer.a will be built.

Right now there are no separate c++ client development package with shared library and  headers, so to build reindexer client it is necessary to keep whole reindexer repository.

Here is sample client application:

````c++

#include "reindexer.h"

using namespace reindexer;

int main () {
    // Initialize database
    auto db = std::shared_ptr<Reindexer> (new Reindexer);
    // Create namespace and add index
    db->OpenNamespace ("mytable");
    db->AddIndex ("mytable",{"id","id","hash","int",IndexOpts().PK()});

    // Insert some data
    auto item = std::unique_ptr<Item>(db->NewItem ("mytable"));
    string data = "{\"id\":100,\"name\":\"Some name\"}";
    item->FromJSON (data);
    db->Upsert ("mytable",item.get());

    // Build & execute query
    auto query = Query("mytable").Where ("id",CondEq,100);
    QueryResults results;
    Error err = db->Select (query,results);
    if (!err.ok()) {
        printf ("select error: %s",err.what().c_str());
        return -1;
    }

    // Fetch and print results
    for (unsigned i = 0; i < results.size(); i++) {
        auto item = std::unique_ptr<Item> (results.GetItem (0));
        printf ("returned: %s\n",item->GetJSON ().data());
    }
    return 0;
}

````
To compile this snippet use the following g++ command line:

````bash
g++ cli.cc -L reindexer/cpp_src/build -I reindexer/cpp_src -I reindexer/cpp_src/core -I reindexer/cpp_src/vendor -std=c++11 -lreindexer -lleveldb
````

PS. Unfortunately C++ API is not well documented, so if you have any future questions, you are free to ask, and we will try to help. Also you can check reindexer_server sources as example of C++ usage.

**Comment by catroot** [comment]
`-lpthread` is also required for linker.
Thank you for quick resonse!
